application:
  title: '@project.name@'
  version: '@project.version@'

#debug: true
swagger:
  config:
    title: 'Bookshelf API'
    version: '1.0.0'
    capacity: 2000
    license:
      name: 'MIT'
      url: 'https://opensource.org/licenses/MIT'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/bookshelf'
    username: 'birgit'
    password: ${PG_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
  sql:
    init:
      mode: always

  docker:
    compose:
      file: 'compose.yaml'